In [7]:
""" Matrix solver project using Numpy
Aim is to solve linear equations AX = B
- Works for unique , no or infinite solutions
- Tells about matrix rank and determinant """
import numpy as np

In [8]:
# lets take equation 2x + y = 5 and x - y = 1
# --> A = [[2, 1] , [1 , -1]], and B = [[5], 1]]

A = np.array([[2,1],
              [1,-1]], dtype = float)

B = np.array ([[5],
               [1]], dtype = float)

#shape
print("Shape of A :", A.shape)
print("Shape of B :", B.shape)


Shape of A : (2, 2)
Shape of B : (2, 1)


In [9]:
#to display matrices
def show_matrix(name, M):
    print("\n" + name + "=")
    with np.printoptions(precision = 4,suppress= True):
        print(M)
        #Setting printing options temporarily 
        #precision 4 so float only goes upto 4 and
        #suppress true so that v.small numbers are zero

show_matrix("A",A)
show_matrix("B",B)
        


A=
[[ 2.  1.]
 [ 1. -1.]]

B=
[[5.]
 [1.]]


In [12]:
#Functions to check determinant,rank and condition number( to know if matrix is able for operations)
def diagnose_matrix(A,B):
    det= None
    cond= None
    try:
        if A.shape[0] == A.shape[1]:
            det= np.linalg.det(A)
        cond= np.linalg.cond(A)
    except Exception:
            pass

    rankA = np.linalg.matrix_rank(A)
    rankAug= np.linalg.matrix_rank(np.hstack((A,B)))

    print("\n Matrix Diagnosis")
    print("Rank of A:"+ str(rankA))
    print("Rank of [A|B]:"+ str(rankAug))
    if det is not None:
        print("Determinant of A:" +str(det))
    print("Condition number:"+str(cond))

    return det,cond,rankA, rankAug

diagnose_matrix(A,B)




 Matrix Diagnosis
Rank of A:2
Rank of [A|B]:2
Determinant of A:-2.9999999999999996
Condition number:1.7675918792439989


(np.float64(-2.9999999999999996),
 np.float64(1.7675918792439989),
 np.int64(2),
 np.int64(2))

In [14]:
def solve_system(A,B):
    m,n = A.shape
    det,cond,rankA,rankAug= diagnose_matrix(A,B)

    print("Solving system AX=B")

    #1 square matrix and full rank

    if m==n and rankA ==n:
        X= np.linalg.solve(A,B)
        print("Unique solution found")
        return X

    #2 Incocsistent system
    if rankA!=rankAug:
        print("No solution exist")
        return None

    #3 infinite solution
    if rankA== rankAug and rankA < n:
        X_part,residuals,*_=np.linalg.lstsq(A,B,rcond=None)
    #  "*_" --> "*" takes all remaining outputs and "_" ignores them
        print("Infinite solutions - showing one particular solution")
        return X_part


    #4 least squares(best fit)
    X_lstsq,residuals,*_= np.linalg.lstsq(A,B,rcond=None)
    print("best approximate solution:")
    return X_lstsq

X= solve_system(A,B)
show_matrix("X(solution)", X)



 Matrix Diagnosis
Rank of A:2
Rank of [A|B]:2
Determinant of A:-2.9999999999999996
Condition number:1.7675918792439989
Solving system AX=B
Unique solution found

X(solution)=
[[2.]
 [1.]]


outcome:
- solved a equation using numpy
- now I need to solve different equations using this method
- need to make a function to take equation as input from user